# production settings

# no h2 console in production
spring.h2.console.enabled=false

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:skel
spring.datasource.user=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

# do we have logging at all?
logging.level.root=INFO


############### for prod #######################
# frontend served by backend; no cors calls expected; i.e. same origin expected
cors.allowed-origins=
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=Authorization,Content-Type
cors.allow-credentials=true
cors.max-age=1800


# JWT Properties
# overridden via env var / deployment
app.jwt.secret=${APP_JWT_SECRET}
# 1h (for prod)
app.jwt.expirationMs=3600000
# important: whitespace at end part of prefix!
app.jwt.token.prefix=Bearer 
app.jwt.token.header=Authorization
app.jwt.token.type=JWT
app.jwt.token.issuer=skel-api
app.jwt.token.audience=skel-ui
app.jwt.login.url=/authentication/login
