// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { addAllToShoppingCart, authenticateUser, cancelOrder, clearShoppingCart, confirmOrder, createOrder, createProduct, createReview, createUser, deleteProduct, deleteProductFromShoppingCart, deleteReview, deleteUser, deleteUserProductSubscription, getAllManagers, getAllOrders, getAllUsers, getCurrentUser, getOrderById, getOrders, getProductById, getProducts, getReviews, getShoppingCart, getUser, isAuthenticated, type Options, register, subscribe, unsubscribe, updateProduct, updateProductInShoppingCart, updateSubscription, updateUser } from '../sdk.gen';
import type { AddAllToShoppingCartData, AuthenticateUserData, AuthenticateUserResponse, CancelOrderData, CancelOrderResponse, ClearShoppingCartData, ConfirmOrderData, ConfirmOrderResponse, CreateOrderData, CreateOrderResponse, CreateProductData, CreateProductResponse, CreateReviewData, CreateReviewResponse, CreateUserData, CreateUserResponse, DeleteProductData, DeleteProductFromShoppingCartData, DeleteReviewData, DeleteUserData, DeleteUserProductSubscriptionData, GetAllManagersData, GetAllManagersResponse, GetAllOrdersData, GetAllOrdersResponse, GetAllUsersData, GetAllUsersResponse, GetCurrentUserData, GetCurrentUserResponse, GetOrderByIdData, GetOrderByIdResponse, GetOrdersData, GetOrdersResponse, GetProductByIdData, GetProductByIdResponse, GetProductsData, GetProductsResponse, GetReviewsData, GetReviewsResponse, GetShoppingCartData, GetShoppingCartResponse, GetUserData, GetUserResponse, IsAuthenticatedData, IsAuthenticatedResponse, RegisterData, RegisterResponse, SubscribeData, UnsubscribeData, UpdateProductData, UpdateProductInShoppingCartData, UpdateProductResponse, UpdateSubscriptionData, UpdateUserData, UpdateUserResponse } from '../types.gen';

export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, DefaultError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, DefaultError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authenticateUserMutation = (options?: Partial<Options<AuthenticateUserData>>): UseMutationOptions<AuthenticateUserResponse, DefaultError, Options<AuthenticateUserData>> => {
    const mutationOptions: UseMutationOptions<AuthenticateUserResponse, DefaultError, Options<AuthenticateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authenticateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateSubscriptionMutation = (options?: Partial<Options<UpdateSubscriptionData>>): UseMutationOptions<unknown, DefaultError, Options<UpdateSubscriptionData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UpdateSubscriptionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateSubscription({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const subscribeMutation = (options?: Partial<Options<SubscribeData>>): UseMutationOptions<unknown, DefaultError, Options<SubscribeData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SubscribeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await subscribe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createReviewMutation = (options?: Partial<Options<CreateReviewData>>): UseMutationOptions<CreateReviewResponse, DefaultError, Options<CreateReviewData>> => {
    const mutationOptions: UseMutationOptions<CreateReviewResponse, DefaultError, Options<CreateReviewData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createReview({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const confirmOrderMutation = (options?: Partial<Options<ConfirmOrderData>>): UseMutationOptions<ConfirmOrderResponse, DefaultError, Options<ConfirmOrderData>> => {
    const mutationOptions: UseMutationOptions<ConfirmOrderResponse, DefaultError, Options<ConfirmOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await confirmOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const cancelOrderMutation = (options?: Partial<Options<CancelOrderData>>): UseMutationOptions<CancelOrderResponse, DefaultError, Options<CancelOrderData>> => {
    const mutationOptions: UseMutationOptions<CancelOrderResponse, DefaultError, Options<CancelOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await cancelOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createOrderMutation = (options?: Partial<Options<CreateOrderData>>): UseMutationOptions<CreateOrderResponse, DefaultError, Options<CreateOrderData>> => {
    const mutationOptions: UseMutationOptions<CreateOrderResponse, DefaultError, Options<CreateOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createProductMutation = (options?: Partial<Options<CreateProductData>>): UseMutationOptions<CreateProductResponse, DefaultError, Options<CreateProductData>> => {
    const mutationOptions: UseMutationOptions<CreateProductResponse, DefaultError, Options<CreateProductData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createProduct({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const clearShoppingCartMutation = (options?: Partial<Options<ClearShoppingCartData>>): UseMutationOptions<unknown, DefaultError, Options<ClearShoppingCartData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<ClearShoppingCartData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await clearShoppingCart({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getShoppingCartQueryKey = (options?: Options<GetShoppingCartData>) => createQueryKey('getShoppingCart', options);

export const getShoppingCartOptions = (options?: Options<GetShoppingCartData>) => queryOptions<GetShoppingCartResponse, DefaultError, GetShoppingCartResponse, ReturnType<typeof getShoppingCartQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getShoppingCart({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getShoppingCartQueryKey(options)
});

export const addAllToShoppingCartMutation = (options?: Partial<Options<AddAllToShoppingCartData>>): UseMutationOptions<unknown, DefaultError, Options<AddAllToShoppingCartData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AddAllToShoppingCartData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addAllToShoppingCart({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createUserMutation = (options?: Partial<Options<CreateUserData>>): UseMutationOptions<CreateUserResponse, DefaultError, Options<CreateUserData>> => {
    const mutationOptions: UseMutationOptions<CreateUserResponse, DefaultError, Options<CreateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteProductMutation = (options?: Partial<Options<DeleteProductData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteProductData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteProductData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteProduct({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateProductMutation = (options?: Partial<Options<UpdateProductData>>): UseMutationOptions<UpdateProductResponse, DefaultError, Options<UpdateProductData>> => {
    const mutationOptions: UseMutationOptions<UpdateProductResponse, DefaultError, Options<UpdateProductData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateProduct({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteProductFromShoppingCartMutation = (options?: Partial<Options<DeleteProductFromShoppingCartData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteProductFromShoppingCartData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteProductFromShoppingCartData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteProductFromShoppingCart({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateProductInShoppingCartMutation = (options?: Partial<Options<UpdateProductInShoppingCartData>>): UseMutationOptions<unknown, DefaultError, Options<UpdateProductInShoppingCartData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UpdateProductInShoppingCartData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateProductInShoppingCart({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteUserMutation = (options?: Partial<Options<DeleteUserData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserQueryKey = (options: Options<GetUserData>) => createQueryKey('getUser', options);

export const getUserOptions = (options: Options<GetUserData>) => queryOptions<GetUserResponse, DefaultError, GetUserResponse, ReturnType<typeof getUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserQueryKey(options)
});

export const updateUserMutation = (options?: Partial<Options<UpdateUserData>>): UseMutationOptions<UpdateUserResponse, DefaultError, Options<UpdateUserData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserResponse, DefaultError, Options<UpdateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) => createQueryKey('getCurrentUser', options);

export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => queryOptions<GetCurrentUserResponse, DefaultError, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserQueryKey(options)
});

export const isAuthenticatedQueryKey = (options?: Options<IsAuthenticatedData>) => createQueryKey('isAuthenticated', options);

export const isAuthenticatedOptions = (options?: Options<IsAuthenticatedData>) => queryOptions<IsAuthenticatedResponse, DefaultError, IsAuthenticatedResponse, ReturnType<typeof isAuthenticatedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await isAuthenticated({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: isAuthenticatedQueryKey(options)
});

export const getProductByIdQueryKey = (options: Options<GetProductByIdData>) => createQueryKey('getProductById', options);

export const getProductByIdOptions = (options: Options<GetProductByIdData>) => queryOptions<GetProductByIdResponse, DefaultError, GetProductByIdResponse, ReturnType<typeof getProductByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProductById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductByIdQueryKey(options)
});

export const getReviewsQueryKey = (options: Options<GetReviewsData>) => createQueryKey('getReviews', options);

export const getReviewsOptions = (options: Options<GetReviewsData>) => queryOptions<GetReviewsResponse, DefaultError, GetReviewsResponse, ReturnType<typeof getReviewsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getReviews({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getReviewsQueryKey(options)
});

export const getProductsQueryKey = (options: Options<GetProductsData>) => createQueryKey('getProducts', options);

export const getProductsOptions = (options: Options<GetProductsData>) => queryOptions<GetProductsResponse, DefaultError, GetProductsResponse, ReturnType<typeof getProductsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProducts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductsQueryKey(options)
});

export const getOrdersQueryKey = (options: Options<GetOrdersData>) => createQueryKey('getOrders', options);

export const getOrdersOptions = (options: Options<GetOrdersData>) => queryOptions<GetOrdersResponse, DefaultError, GetOrdersResponse, ReturnType<typeof getOrdersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOrders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOrdersQueryKey(options)
});

export const getOrderByIdQueryKey = (options: Options<GetOrderByIdData>) => createQueryKey('getOrderById', options);

export const getOrderByIdOptions = (options: Options<GetOrderByIdData>) => queryOptions<GetOrderByIdResponse, DefaultError, GetOrderByIdResponse, ReturnType<typeof getOrderByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOrderById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOrderByIdQueryKey(options)
});

export const getAllUsersQueryKey = (options?: Options<GetAllUsersData>) => createQueryKey('getAllUsers', options);

export const getAllUsersOptions = (options?: Options<GetAllUsersData>) => queryOptions<GetAllUsersResponse, DefaultError, GetAllUsersResponse, ReturnType<typeof getAllUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllUsersQueryKey(options)
});

export const getAllOrdersQueryKey = (options: Options<GetAllOrdersData>) => createQueryKey('getAllOrders', options);

export const getAllOrdersOptions = (options: Options<GetAllOrdersData>) => queryOptions<GetAllOrdersResponse, DefaultError, GetAllOrdersResponse, ReturnType<typeof getAllOrdersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllOrders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllOrdersQueryKey(options)
});

export const getAllManagersQueryKey = (options?: Options<GetAllManagersData>) => createQueryKey('getAllManagers', options);

export const getAllManagersOptions = (options?: Options<GetAllManagersData>) => queryOptions<GetAllManagersResponse, DefaultError, GetAllManagersResponse, ReturnType<typeof getAllManagersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllManagers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllManagersQueryKey(options)
});

export const deleteReviewMutation = (options?: Partial<Options<DeleteReviewData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteReviewData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteReviewData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteReview({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const unsubscribeMutation = (options?: Partial<Options<UnsubscribeData>>): UseMutationOptions<unknown, DefaultError, Options<UnsubscribeData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UnsubscribeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await unsubscribe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteUserProductSubscriptionMutation = (options?: Partial<Options<DeleteUserProductSubscriptionData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteUserProductSubscriptionData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteUserProductSubscriptionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUserProductSubscription({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
