-- Insert users into USERX table
INSERT INTO USERX (ID, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE) 
VALUES (1000, TRUE, 'Admin', 'Istrator', 'passwd', 'admin', 1000, '2024-01-01 00:00:00');

INSERT INTO USERX (ID, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (6000, TRUE, 'Admin2', 'Istrator', 'passwd', 'admin2', 1000, '2024-01-01 00:00:00');

INSERT INTO USERX (ID, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE) 
VALUES (2000, TRUE, 'Susi', 'Kaufgern', 'passwd', 'user1', 1000, '2024-01-01 00:00:00');

INSERT INTO USERX (ID, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE) 
VALUES (3000, TRUE, 'Max', 'Mustermann', 'passwd', 'user2', 1000, '2024-01-01 00:00:00');

INSERT INTO USERX (ID, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE) 
VALUES (4000, TRUE, 'Elvis', 'The King', 'passwd', 'elvis', 1000, '2024-01-01 00:00:00');

INSERT INTO userx (id, ENABLED, FIRST_NAME, LAST_NAME,  username, password, CREATE_USER_ID, CREATE_DATE)
VALUES (5000, TRUE, 'Jonny', 'Denber', 'jonny', '$2a$10$xyz...', 1000, '2024-01-01 00:00:00');

-- Insert roles into USERX_USERX_ROLE table by looking up the corresponding user ID
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'MANAGER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'jonny'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin2'), 'ADMIN');

-- Insert products into the PRODUCT table
INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (1000, 'Iphone 15', 580.99, 1, 0, 'Apple Iphone 15', 'This is an Apple Iphone 15', 'https://www.google.com/', '2024-01-01 00:00:00', 2.0);

INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (2000, 'Iphone 12', 280.99, 9, 0, 'Apple Iphone 12', 'This is an Apple Iphone 12', 'https://www.google.com/', '2024-01-01 00:00:00', 3.0);

INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (3000, 'Iphone 14', 480.99, 5, 0.3, 'Apple Iphone 14', 'This is an Apple Iphone 14', 'https://www.google.com/', '2024-01-01 00:00:00', 2.0);

INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (4000, 'Iphone 13', 380.99, 10, 0.1, 'Apple Iphone 13', 'This is an Apple Iphone 13', 'https://www.google.com/', '2024-01-01 00:00:00', 5.0);

INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (5000, 'Iphone 10', 380.99, 4, 0, 'Apple Iphone 10', 'This is an Apple Iphone 13', 'https://www.google.com/', '2024-01-01 00:00:00', 5.0);

INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (6000, 'Iphone 9', 380.99, 4, 0, 'Apple Iphone 9', 'This is an Apple Iphone 13', 'https://www.google.com/', '2024-01-01 00:00:00', 5.0);


-- Insert into cartItems
INSERT INTO cart_item (id, user_id, product_id, quantity)
VALUES (1000, 5000, 5000, 3);

INSERT INTO cart_item (id, user_id, product_id, quantity)
VALUES (2000, 2000, 6000, 6);

-- Insert into ORDERS
INSERT INTO orders (id, user_id, status, sum, created_date)
VALUES (9000, 5000, 'PENDING_PAYMENT', 100.00, CURRENT_TIMESTAMP);

INSERT INTO orders (id, user_id, status, sum, created_date)
VALUES (8000, 2000, 'PENDING_PAYMENT', 100.00, CURRENT_TIMESTAMP);

INSERT INTO orders (id, user_id, status, sum, created_date)
VALUES (7000, 4000, 'CANCELLED', 100.00, CURRENT_TIMESTAMP);

-- Insert into Order_Item
INSERT INTO order_item (id, order_id, product_id, quantity, name, price)
VALUES (9000, 9000, 5000, 2, 'Storno-Produkt', 50.0);

-- Insert reviews into the REVIEW table
-- Reviews for Iphone 15 (ID: 1000) - Avg Rating in Product table is 2.0
INSERT INTO REVIEW (ID, PRODUCT_ID, AUTHOR_ID, RATING, TITLE, COMMENT, CREATED_DATE)
VALUES (1000, 1000, 2000, 1, 'Overheating issues', 'The phone gets really hot after 10 minutes of use.', '2024-01-10 10:00:00');

INSERT INTO REVIEW (ID, PRODUCT_ID, AUTHOR_ID, RATING, TITLE, COMMENT, CREATED_DATE)
VALUES (2000, 1000, 3000, 3, 'It is okay', 'Not much different from the previous version.', '2024-01-12 14:30:00');

-- Reviews for Iphone 12 (ID: 2000) - Avg Rating in Product table is 3.0
INSERT INTO REVIEW (ID, PRODUCT_ID, AUTHOR_ID, RATING, TITLE, COMMENT, CREATED_DATE)
VALUES (3000, 2000, 4000, 3, 'Good budget option', 'Good value for money now that the price dropped.', '2024-01-15 09:00:00');

-- Reviews for Iphone 13 (ID: 4000) - Avg Rating in Product table is 5.0
INSERT INTO REVIEW (ID, PRODUCT_ID, AUTHOR_ID, RATING, TITLE, COMMENT, CREATED_DATE)
VALUES (4000, 4000, 2000, 5, 'Perfect', 'Battery life is amazing and the camera is great.', '2024-01-20 18:15:00');

INSERT INTO REVIEW (ID, PRODUCT_ID, AUTHOR_ID, RATING, TITLE, COMMENT, CREATED_DATE)
VALUES (5000, 4000, 4000, 5, 'Love it', 'Best phone I have ever owned. Elvis approves.', '2024-01-21 11:45:00');

-- Review for Iphone 14 (ID: 3000) - Avg Rating in Product table is 2.0
INSERT INTO REVIEW (ID, PRODUCT_ID, AUTHOR_ID, RATING, TITLE, COMMENT, CREATED_DATE)
VALUES (6000, 3000, 3000, 2, 'Meh', 'I should have bought the 13 or waited for the 15.', '2024-01-25 16:20:00');
