ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID DROP NOT NULL;

-- Insert users into USERX table
INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATED_DATE, ROLE)
VALUES (TRUE, 'Admin', 'Istrator', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'admin', NULL, '2024-01-01 00:00:00', 'ADMIN');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATED_DATE, ROLE)
VALUES (TRUE, 'Susi', 'Kaufgern', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user1', NULL, '2024-01-01 00:00:00', 'MANAGER');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATED_DATE, ROLE)
VALUES (TRUE, 'Max', 'Mustermann', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user2', NULL, '2024-01-01 00:00:00', 'CUSTOMER');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATED_DATE, ROLE)
VALUES (TRUE, 'Elvis', 'The King', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'elvis', NULL, '2024-01-01 00:00:00', 'ADMIN');

-- Update CREATE_USER_ID fields after the initial insert
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'admin';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'user1';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'user2';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis') WHERE USERNAME = 'elvis';

-- Add the not null constraint back
ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID SET NOT NULL;

INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (1000, 'Iphone 15', 580.99, 1, 0, 'Apple Iphone 15', 'This is an Apple Iphone 15', 'https://www.google.com/', '2024-01-01 00:00:00', 2.0);

INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (2000, 'Iphone 12', 280.99, 9, 0, 'Apple Iphone 12', 'This is an Apple Iphone 12', 'https://www.google.com/', '2024-01-01 00:00:00', 3.0);

INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (3000, 'Iphone 14', 480.99, 5, 0.3, 'Apple Iphone 14', 'This is an Apple Iphone 14', 'https://www.google.com/', '2024-01-01 00:00:00', 2.0);

INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (4000, 'Iphone 13', 380.99, 10, 0.1, 'Apple Iphone 13', 'This is an Apple Iphone 13', 'https://www.google.com/', '2024-01-01 00:00:00', 5.0);

INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (5000, 'Iphone 16', 380.99, 4, 0, 'Apple Iphone 10', 'This is an Apple Iphone 13', 'https://www.google.com/', '2024-01-01 00:00:00', 5.0);

INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK, DISCOUNT, SHORT_DESCRIPTION, DESCRIPTION, IMAGE_URL, CREATED_DATE, RATING)
VALUES (6000, 'Iphone 17', 380.99, 4, 0, 'Apple Iphone 9', 'This is an Apple Iphone 13', 'https://www.google.com/', '2024-01-01 00:00:00', 5.0);

-- Insert Orders for User1
INSERT INTO ORDERS (ID, USER_ID, STATUS, SUM, CREATED_DATE)
VALUES (9000, (SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'PENDING', 100.00, '2024-01-25 16:20:00');

INSERT INTO ORDERS (ID, USER_ID, STATUS, SUM, CREATED_DATE)
VALUES (8000, (SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'PENDING_PAYMENT', 100.00, '2024-01-25 16:20:00');

INSERT INTO ORDERS (ID, USER_ID, STATUS, SUM, CREATED_DATE)
VALUES (7000, (SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'CANCELLED', 100.00, '2024-01-25 16:20:00');

-- Insert into Order_Item
INSERT INTO ORDER_ITEM (ID, ORDER_ID, PRODUCT_ID, QUANTITY, NAME, TOTAL)
VALUES (9000, 9000, 5000, 2, 'Storno-Produkt', 50.0);

INSERT INTO ORDER_ITEM (ID, ORDER_ID, PRODUCT_ID, QUANTITY, NAME, TOTAL)
VALUES (8000, 8000, 3000, 2, 'Storno-Produkt', 50.0);

INSERT INTO ORDER_ITEM (ID, ORDER_ID, PRODUCT_ID, QUANTITY, NAME, TOTAL)
VALUES (7000, 7000, 5000, 2, 'Storno-Produkt', 50.0);

