// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddAllToShoppingCartData, AddAllToShoppingCartResponses, AuthenticateUserData, AuthenticateUserResponses, CancelOrderData, CancelOrderResponses, ClearShoppingCartData, ClearShoppingCartResponses, ConfirmOrderData, ConfirmOrderResponses, CreateCurrentUserData, CreateCurrentUserResponses, CreateOrderData, CreateOrderResponses, CreateProductData, CreateProductResponses, CreateReviewData, CreateReviewResponses, CreateUserData, CreateUserResponses, DeleteProductData, DeleteProductFromShoppingCartData, DeleteProductFromShoppingCartResponses, DeleteProductResponses, DeleteReviewData, DeleteReviewResponses, DeleteUserData, DeleteUserResponses, GetAllManagersData, GetAllManagersResponses, GetAllOrdersData, GetAllOrdersResponses, GetAllUsersData, GetAllUsersResponses, GetCurrentUserData, GetCurrentUserResponses, GetOrdersData, GetOrdersResponses, GetProductByIdData, GetProductByIdResponses, GetProductsData, GetProductsResponses, GetReviewsData, GetReviewsResponses, GetShoppingCartData, GetShoppingCartResponses, GetUserData, GetUserResponses, IsAuthenticatedData, IsAuthenticatedResponses, SubscribeData, SubscribeResponses, UpdateCurrentUserData, UpdateCurrentUserResponses, UpdateProductData, UpdateProductInShoppingCartData, UpdateProductInShoppingCartResponses, UpdateProductResponses, UpdateSubscriptionData, UpdateSubscriptionResponses, UpdateUserData, UpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const authenticateUser = <ThrowOnError extends boolean = false>(options: Options<AuthenticateUserData, ThrowOnError>) => (options.client ?? client).post<AuthenticateUserResponses, unknown, ThrowOnError>({
    url: '/authentication/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>) => (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({ url: '/api/users/me', ...options });

export const updateCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<UpdateCurrentUserData, ThrowOnError>) => (options?.client ?? client).patch<UpdateCurrentUserResponses, unknown, ThrowOnError>({ url: '/api/users/me', ...options });

export const createCurrentUser = <ThrowOnError extends boolean = false>(options: Options<CreateCurrentUserData, ThrowOnError>) => (options.client ?? client).post<CreateCurrentUserResponses, unknown, ThrowOnError>({
    url: '/api/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const updateSubscription = <ThrowOnError extends boolean = false>(options: Options<UpdateSubscriptionData, ThrowOnError>) => (options.client ?? client).patch<UpdateSubscriptionResponses, unknown, ThrowOnError>({ url: '/api/product/{id}/subscribe', ...options });

export const subscribe = <ThrowOnError extends boolean = false>(options: Options<SubscribeData, ThrowOnError>) => (options.client ?? client).post<SubscribeResponses, unknown, ThrowOnError>({ url: '/api/product/{id}/subscribe', ...options });

export const createReview = <ThrowOnError extends boolean = false>(options: Options<CreateReviewData, ThrowOnError>) => (options.client ?? client).post<CreateReviewResponses, unknown, ThrowOnError>({
    url: '/api/product/{id}/createReview',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const confirmOrder = <ThrowOnError extends boolean = false>(options: Options<ConfirmOrderData, ThrowOnError>) => (options.client ?? client).post<ConfirmOrderResponses, unknown, ThrowOnError>({
    url: '/api/orders/{orderId}/confirm',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const cancelOrder = <ThrowOnError extends boolean = false>(options: Options<CancelOrderData, ThrowOnError>) => (options.client ?? client).post<CancelOrderResponses, unknown, ThrowOnError>({ url: '/api/orders/{orderId}/cancel', ...options });

export const createOrder = <ThrowOnError extends boolean = false>(options?: Options<CreateOrderData, ThrowOnError>) => (options?.client ?? client).post<CreateOrderResponses, unknown, ThrowOnError>({ url: '/api/orders/createOrder', ...options });

export const createProduct = <ThrowOnError extends boolean = false>(options: Options<CreateProductData, ThrowOnError>) => (options.client ?? client).post<CreateProductResponses, unknown, ThrowOnError>({
    url: '/api/manager/createProduct',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const clearShoppingCart = <ThrowOnError extends boolean = false>(options?: Options<ClearShoppingCartData, ThrowOnError>) => (options?.client ?? client).delete<ClearShoppingCartResponses, unknown, ThrowOnError>({ url: '/api/cart', ...options });

export const getShoppingCart = <ThrowOnError extends boolean = false>(options?: Options<GetShoppingCartData, ThrowOnError>) => (options?.client ?? client).get<GetShoppingCartResponses, unknown, ThrowOnError>({ url: '/api/cart', ...options });

export const addAllToShoppingCart = <ThrowOnError extends boolean = false>(options: Options<AddAllToShoppingCartData, ThrowOnError>) => (options.client ?? client).post<AddAllToShoppingCartResponses, unknown, ThrowOnError>({
    url: '/api/cart',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => (options.client ?? client).post<CreateUserResponses, unknown, ThrowOnError>({
    url: '/api/admin/createUser',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteProduct = <ThrowOnError extends boolean = false>(options: Options<DeleteProductData, ThrowOnError>) => (options.client ?? client).delete<DeleteProductResponses, unknown, ThrowOnError>({ url: '/api/manager/product/{id}', ...options });

export const updateProduct = <ThrowOnError extends boolean = false>(options: Options<UpdateProductData, ThrowOnError>) => (options.client ?? client).patch<UpdateProductResponses, unknown, ThrowOnError>({
    url: '/api/manager/product/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteProductFromShoppingCart = <ThrowOnError extends boolean = false>(options: Options<DeleteProductFromShoppingCartData, ThrowOnError>) => (options.client ?? client).delete<DeleteProductFromShoppingCartResponses, unknown, ThrowOnError>({ url: '/api/cart/{productId}', ...options });

export const updateProductInShoppingCart = <ThrowOnError extends boolean = false>(options: Options<UpdateProductInShoppingCartData, ThrowOnError>) => (options.client ?? client).patch<UpdateProductInShoppingCartResponses, unknown, ThrowOnError>({ url: '/api/cart/{productId}', ...options });

export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserResponses, unknown, ThrowOnError>({ url: '/api/admin/user/{id}', ...options });

export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => (options.client ?? client).get<GetUserResponses, unknown, ThrowOnError>({ url: '/api/admin/user/{id}', ...options });

export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>) => (options.client ?? client).patch<UpdateUserResponses, unknown, ThrowOnError>({
    url: '/api/admin/user/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const isAuthenticated = <ThrowOnError extends boolean = false>(options?: Options<IsAuthenticatedData, ThrowOnError>) => (options?.client ?? client).get<IsAuthenticatedResponses, unknown, ThrowOnError>({ url: '/api/users/authenticated', ...options });

export const getProductById = <ThrowOnError extends boolean = false>(options: Options<GetProductByIdData, ThrowOnError>) => (options.client ?? client).get<GetProductByIdResponses, unknown, ThrowOnError>({ url: '/api/product/{id}', ...options });

export const getReviews = <ThrowOnError extends boolean = false>(options: Options<GetReviewsData, ThrowOnError>) => (options.client ?? client).get<GetReviewsResponses, unknown, ThrowOnError>({ url: '/api/product/{id}/reviews', ...options });

export const getProducts = <ThrowOnError extends boolean = false>(options: Options<GetProductsData, ThrowOnError>) => (options.client ?? client).get<GetProductsResponses, unknown, ThrowOnError>({ url: '/api/product/products', ...options });

export const getOrders = <ThrowOnError extends boolean = false>(options: Options<GetOrdersData, ThrowOnError>) => (options.client ?? client).get<GetOrdersResponses, unknown, ThrowOnError>({ url: '/api/orders', ...options });

export const getAllOrders = <ThrowOnError extends boolean = false>(options: Options<GetAllOrdersData, ThrowOnError>) => (options.client ?? client).get<GetAllOrdersResponses, unknown, ThrowOnError>({ url: '/api/manager/orders', ...options });

export const getAllUsers = <ThrowOnError extends boolean = false>(options?: Options<GetAllUsersData, ThrowOnError>) => (options?.client ?? client).get<GetAllUsersResponses, unknown, ThrowOnError>({ url: '/api/admin/users', ...options });

export const getAllManagers = <ThrowOnError extends boolean = false>(options?: Options<GetAllManagersData, ThrowOnError>) => (options?.client ?? client).get<GetAllManagersResponses, unknown, ThrowOnError>({ url: '/api/admin/managers', ...options });

export const deleteReview = <ThrowOnError extends boolean = false>(options: Options<DeleteReviewData, ThrowOnError>) => (options.client ?? client).delete<DeleteReviewResponses, unknown, ThrowOnError>({ url: '/api/product/{productId}/review/{reviewId}', ...options });
