@startuml

actor Customer
participant OrderService
participant ProductService
participant ProductRepository
participant Order
participant OrderRepository

Customer -> OrderService: order(shoppingCart: ShoppingCart)
OrderService -> Order: new
Order --> OrderService: new [o: Order]
loop For each CartItem c in shoppingCart
    OrderService -> ProductService: checkAvailability(c: CartItem)
    ProductService -> ProductRepository: checkAvailabilityAndReduceProductQuantity(product: Product, quantity: int)
    ProductRepository --> ProductService: checkAvailabilityAndReduceProductQuantity: [status: unavailable or available]
    note left
        this is important because to ensure
        atomicity
    end note
    ProductService --> OrderService: checkAvailability: [status: unavailable or available]
    alt status == available
        OrderService -> OrderService: addToOrder(o: Order, c: CartItem)
    else status == unavailable
        OrderService -> OrderService: addToNotInStock(o: Order, c: CartItem)
    end
end

OrderService -> OrderService: setOrderStatus(o: Order, s: OrderStatus = PENDING)

OrderService -> OrderRepository: saveOrder(o: Order)
OrderRepository --> OrderService: ok

OrderService --> Customer: order: [order overview]

alt user wants to place the order
    Customer -> OrderService: executeOrder(o: Order)
    OrderService -> OrderService: setOrderStatus(o: Order, s: OrderStatus = PENDING_PAYMENT)
    OrderService -> OrderRepository: saveOrder(o: Order)
    OrderRepository --> OrderService: ok

    note left
        here the processing would be continued in the
        PaymentProcessing Service
    end note

    OrderService --> Customer: ok
else
    Customer -> OrderService: discardOrder(o: Order)
    OrderService -> OrderRepository: deleteOrder(o: Order)
    OrderRepository --> OrderService: ok

    OrderService --> Customer: ok
end

@enduml
