@startuml

actor Customer
participant OrderService
participant ProductService
participant ProductRepository
participant Order
participant OrderRepository

Customer -> OrderService: createOrder()

OrderService -> ProductService: reserveProducts(c: CartItems)
ProductService -> ProductRepository: tryReserveAllProducts(products: Map<Product, quantity: int>)
ProductRepository --> ProductService: tryReserveAllProducts: [status: allOK | notOK]
note left
    this is important to ensure atomicity
end note
ProductService --> OrderService: reserveProducts: [status: allOK | notOK]
alt status == allOK
    OrderService -> Order: new
    note left
        create order with products
    end note
    Order --> OrderService: new [o: Order]
    OrderService -> OrderService: addAllProducts()
    OrderService -> OrderService: setOrderStatus(o: Order, s: OrderStatus = PENDING)
    OrderService -> OrderRepository: saveOrder(o: Order)
    OrderRepository --> OrderService: ok
    OrderService --> Customer: createOrder: [order overview]
    note left
        customer has to confirm and proceed with payment
    end note
else status == notOK
    OrderService --> Customer: createOrder: [shoppingCart: ShoppingCart]
    note left
        inform Customer that he has to try again
        (go back to start)
    end note
end alt



@enduml
