@startuml

class Userx {
    username: String
    first_name: String
    last_name: String
    email: String
    phone: String
    notifierTypes: ?
}
note right
    notifierTypes probably should be
    implemented with decorator pattern
end note

enum UserxRole {
    ADMIN
    MANAGER
    CUSTOMER
}

class Product {
    name: String
    price: double
    stock: int
    discount: double /'in interval [0, 1] 0 -> 0%, 1 -> 100% discount'/
    picture: Stub
}
note left
    filtering products done
    in database;

    product creation could be done
    through factoryMethod/abstractFactory
end note

class Review {
    rating: int /'in interval [1, 5]'/
    comment: String
    createDate: LocalDateTime
}

class ShoppingCart {
}

class CartItem {
  quantity: int
}

class Order {
    createDate: LocalDateTime
    sum: double
}

enum OrderStatus {
    PENDING
    PENDING_PAYMENT
    PROCESSING
    SHIPPED
    DELIVERED
    CANCELLED
}

class ProductSubscriptions {
}
note left
    observer pattern
end note

enum ProductSubscriptionsType {
    DISCOUNT_ProductSubscriptions
    BACK_IN_STOCK_ProductSubscriptions
}

'associations:
Userx -- "1" UserxRole: role
Userx -- "1" ShoppingCart: shoppingCart

Userx .. Review: writes (role = CUSTOMER)
Userx .. Order: places (role = CUSTOMER)
Userx .. Product: manages (role = MANAGER)

Review -- "1" Userx: author

Product -- "0..*" Review: reviews

ShoppingCart -- "0..*" CartItem: items
CartItem -- "1" Product: product

Order -- "1" OrderStatus: status
Order -- "1" ShoppingCart: shoppingCart

ProductSubscriptions -- "1" Userx: user
ProductSubscriptions -- "1" Product: product
ProductSubscriptions -- "1..*" ProductSubscriptionsType: types: Set<ProductSubscriptionsType>

@enduml